wip

diff --git a/examples/LJ/Makefile b/examples/LJ/Makefile
--- a/examples/LJ/Makefile
+++ b/examples/LJ/Makefile
@@ -2,26 +2,36 @@
 
 SHELL:=/bin/bash
 LOGIC=lj.txt
-TESTS=tests
-SUCCESS=p0.txt p1.txt p2.txt p3.txt p4.txt p5.txt p6.txt
-FAILURE=f0.txt f1.txt f2.txt f3.txt
-EXEC=eval $$(opam env); dune exec pgeon -- $(LOGIC)
+USAT=tests/p0.txt tests/p1.txt tests/p2.txt tests/p3.txt tests/p4.txt tests/p5.txt tests/p6.txt
+UNSATLOG=$(patsubst %.txt,%.txt.log,$(USAT))
+SAT=tests/f0.txt tests/f1.txt tests/f2.txt tests/f3.txt
+SATLOG=$(patsubst %.txt,%.txt.log,$(SAT))
+EXEC=dune exec pgeon -- $(LOGIC)
 
-all: success failure
+all: unsat sat clean
 
-success:
-	-@echo -e "\033[1;33m>>>> Testing success files:\033[0;39m"; \
-        for i in $(SUCCESS); do echo -n "Testing $$i: "; \
-        $(EXEC) $(TESTS)/$$i > tmp.res 2>&1; \
-        res=`grep "Success" tmp.res`; rm tmp.res; \
-        echo -e "\033[32m$$res\033[39m"; done
+%.log: %
+	@timeout 1 $(EXEC) $< > $@ 2>/dev/null || echo "Timeout" > $@
 
-failure:
-	-@echo -e "\033[1;33m>>>> Testing failure files:\033[0;39m"; \
-        for i in $(FAILURE); do echo -n "Testing $$i: "; \
-        $(EXEC) $(TESTS)/$$i > tmp.res 2>&1; \
-        res=`grep "Failure" tmp.res`; rm tmp.res; \
-        echo -e "\033[31m$$res\033[39m"; done
+unsat: $(UNSATLOG)
+	@echo -e "\033[1;33m>>>> Testing success files:\033[0;39m";
+	@for i in $^; do \
+		echo -n "$$i: "; \
+		grep Success $$i > /dev/null && echo -e "\033[32mSuccess\033[39m"; \
+		grep Failure $$i > /dev/null && echo -e "\033[33mFailure\033[39m"; \
+		grep Timeout $$i > /dev/null && echo -e "\033[33mTimeout\033[39m"; \
+		true; \
+		done
+
+sat: $(SATLOG)
+	@echo -e "\033[1;33m>>>> Testing failure files:\033[0;39m";
+	@for i in $^; do \
+		echo -n "$$i: "; \
+		grep Success $$i > /dev/null && echo -e "\033[32mSuccess\033[39m"; \
+		grep Failure $$i > /dev/null && echo -e "\033[31mFailure\033[39m"; \
+		grep Timeout $$i > /dev/null && echo -e "\033[33mTimeout\033[39m"; \
+		true; \
+		done
 
 clean:
-	rm *~ $(TESTS)/*~
+	@ rm -f $(SATLOG) $(UNSATLOG)
